package com.example.demo.model;

import javax.persistence.*;

@Table(name = "gen")
public class Gen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen.id
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen.name
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen.lastName
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen.sex
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen.id
     *
     * @return the value of gen.id
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen.id
     *
     * @param id the value for gen.id
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen.name
     *
     * @return the value of gen.name
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen.name
     *
     * @param name the value for gen.name
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen.lastName
     *
     * @return the value of gen.lastName
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen.lastName
     *
     * @param lastName the value for gen.lastName
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen.sex
     *
     * @return the value of gen.sex
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen.sex
     *
     * @param sex the value for gen.sex
     *
     * @mbg.generated Mon Aug 19 17:08:55 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
}