package com.example.demo.model;

import javax.persistence.*;

@Table(name = "`gen`")
public class Gen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen.id
     *
     * @mbg.generated Mon Aug 19 15:39:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen.name
     *
     * @mbg.generated Mon Aug 19 15:39:48 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen.id
     *
     * @return the value of gen.id
     *
     * @mbg.generated Mon Aug 19 15:39:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen.id
     *
     * @param id the value for gen.id
     *
     * @mbg.generated Mon Aug 19 15:39:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen.name
     *
     * @return the value of gen.name
     *
     * @mbg.generated Mon Aug 19 15:39:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen.name
     *
     * @param name the value for gen.name
     *
     * @mbg.generated Mon Aug 19 15:39:48 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}